language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
       - libcogl-dev
       - libclutter-1.0-dev
       #- mm-common
       #- cluttermm
       - libglademm-2.4-dev

compiler:
  - gcc
  - clang

before_script:
  - ./install-mm-common.sh
  - export PATH=$PATH:$HOME/external/bin
  - export ACLOCAL_PATH="$HOME/external/share/aclocal"
  - ./install-cluttermm.sh

script:
  - make
